### ISSUE TITLE
property 'filter' is undefinded

### ISSUE THREAD

**Issue by emqMalte** [tdorsey/alexa-plex#9]
After Account linking with the PIN - and on all following requests - the lambda function fails:

> TypeError: Cannot read property 'filter' of undefined
at /var/task/lib/plexutils.js:58:47
at _fulfilled (/var/task/node_modules/q/q.js:834:54)
at self.promiseDispatch.done (/var/task/node_modules/q/q.js:863:30)
at Promise.promise.promiseDispatch (/var/task/node_modules/q/q.js:796:13)
at /var/task/node_modules/q/q.js:604:44
at runSingle (/var/task/node_modules/q/q.js:137:13)
at flush (/var/task/node_modules/q/q.js:125:13)
at nextTickCallbackWith0Args (node.js:415:9)
at process._tickDomainCallback (node.js:385:13)

**Comment by tdorsey** [comment]
@EMQcarlos Thanks for the report. We know a bunch of stuff is broken since the code was basically abandoned awhile back. Obviously the "none of this works at all" bugs are first on the list, but afraid I don't really have a timeframe for you on a fix.

**Comment by scbrown** [comment]
@EMQcarlos thanks for letting us know. What version of Plex Media Server are you running? Also, it would help if you could uncomment line #10 in plexutils.js and show us what it logs.

**Comment by tdorsey** [comment]
Did some digging into this, and if no clients are available, the MediaContainer returns zero elements.  There's no error handling for this yet.

@EMQcarlos if you go to ```https://<YourServer>:32400/clients?X-Plex-Token=<YourToken>``` you should see an page with at least one entry in it. If not, make sure your client is visible at that URL before reconfiguring the app (*Alexa, ask \<Skill\> to help*) should reset you. Other things will likely still be broken, but this should move you forward.
